export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { entity, crisis, capex, raror, srb } = req.body;
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    console.error('CRITICAL ERROR: GEMINI_API_KEY is not defined in environment variables.');
    return res.status(500).json({ error: 'Gemini API key not configured on Vercel' });
  }

  const prompt = `You are a world-class strategic consultant (McKinsey/BCG style). Provide a deep, executive analysis in Arabic for the following scenario:
Entity: ${entity}
Crisis Type: ${crisis}
Investment Hedging (CapEx): ${capex}%
RAROR Score: ${raror}
SRB Buffer: ${srb}

Structure the report with these sections in Arabic:
1. Executive Assessment (التقييم التنفيذي الاستراتيجي)
2. Mathematical Modeling Analysis (النمذجة الرياضية وتحليل البيانات)
3. Response Architecture (هيكلية الاستجابة عبر الآفاق الزمنية)
4. Vision 2030 Mapping (الموائمة مع برامج رؤية المملكة 2030)

Use professional, authoritative, and sophisticated Arabic terminology. Return only the report text.`;

  try {
    const response = await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=' + apiKey, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }]
      })
    });

    const data = await response.json();
    
    if (data.error) {
      console.error('Gemini API Error:', data.error);
      return res.status(data.error.code || 500).json({ error: data.error.message });
    }

    const text = data.candidates && data.candidates[0] && data.candidates[0].content && data.candidates[0].content.parts[0] 
      ? data.candidates[0].content.parts[0].text 
      : 'Error: No content generated by AI.';
    
    res.status(200).json({ report: text });
  } catch (error) {
    console.error('Fetch Error:', error);
    res.status(500).json({ error: 'Failed to communicate with Gemini API' });
  }
}
